"""Add occupations table

Revision ID: 009bcc43d7e6
Revises: 2c6cc4833fa2
Create Date: 2023-04-09 22:29:41.473444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009bcc43d7e6'
down_revision = '2c6cc4833fa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_zone', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('education_mode', sa.Integer(), nullable=True),
    sa.Column('education_median', sa.Integer(), nullable=True),
    sa.Column('experience_mode', sa.Integer(), nullable=True),
    sa.Column('experience_median', sa.Integer(), nullable=True),
    sa.Column('style_stress_tolerance', sa.Float(), nullable=True),
    sa.Column('style_achievement_effort', sa.Float(), nullable=True),
    sa.Column('style_social_orientation', sa.Float(), nullable=True),
    sa.Column('style_independence', sa.Float(), nullable=True),
    sa.Column('style_innovation', sa.Float(), nullable=True),
    sa.Column('context_duration_of_typical_work_week', sa.Float(), nullable=True),
    sa.Column('context_outdoors_exposed_to_weather', sa.Float(), nullable=True),
    sa.Column('context_deal_with_unpleasant_or_angry_people', sa.Float(), nullable=True),
    sa.Column('context_exposed_to_hazardous_conditions', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupations_id'), 'occupations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupations_id'), table_name='occupations')
    op.drop_table('occupations')
    # ### end Alembic commands ###
