"""Add ssoc_jobs table

Revision ID: 082466f7d07d
Revises: 15fabb2e57af
Create Date: 2023-05-02 23:58:38.793364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082466f7d07d'
down_revision = '15fabb2e57af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssoc_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('occupation_id', sa.String(), nullable=False),
    sa.Column('ssoc_code', sa.String(), nullable=True),
    sa.Column('ssoc_job_title', sa.String(), nullable=True),
    sa.Column('isco_code', sa.String(), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssoc_jobs_id'), 'ssoc_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssoc_jobs_id'), table_name='ssoc_jobs')
    op.drop_table('ssoc_jobs')
    # ### end Alembic commands ###
