"""test4

Revision ID: 2a58663e8101
Revises: 9ac3260a3c19
Create Date: 2023-10-17 03:13:18.536451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a58663e8101'
down_revision = '9ac3260a3c19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
