"""Add programs table

Revision ID: 328ca9d437be
Revises: 5c7943906638
Create Date: 2023-05-04 23:07:00.841787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328ca9d437be'
down_revision = '5c7943906638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('program_trends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('employment_rate_overall', sa.Float(), nullable=True),
    sa.Column('employment_rate_ft_perm', sa.Float(), nullable=True),
    sa.Column('basic_monthly_mean', sa.Float(), nullable=True),
    sa.Column('basic_monthly_median', sa.Float(), nullable=True),
    sa.Column('gross_monthly_mean', sa.Float(), nullable=True),
    sa.Column('gross_monthly_median', sa.Float(), nullable=True),
    sa.Column('gross_mthly_25_percentile', sa.Float(), nullable=True),
    sa.Column('gross_mthly_75_percentile', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_trends_id'), 'program_trends', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_trends_id'), table_name='program_trends')
    op.drop_table('program_trends')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
