"""create questions table

Revision ID: 3cda552c5044
Revises: 6111621905a4
Create Date: 2023-04-05 20:48:36.019171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cda552c5044'
down_revision = '6111621905a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('min_response_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chats', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'question_id')
    op.drop_table('questions')
    # ### end Alembic commands ###
