"""Add salaries to occupations table

Revision ID: 5c7943906638
Revises: 42ba5e240848
Create Date: 2023-05-04 00:53:17.187589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7943906638'
down_revision = '42ba5e240848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupations', sa.Column('min_salary', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('max_salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupations', 'max_salary')
    op.drop_column('occupations', 'min_salary')
    # ### end Alembic commands ###
