"""test3

Revision ID: 9ac3260a3c19
Revises: a66c463bfaf2
Create Date: 2023-10-17 03:12:39.874922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac3260a3c19'
down_revision = 'a66c463bfaf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
