"""test2

Revision ID: a66c463bfaf2
Revises: a73fd712eb63
Create Date: 2023-10-17 03:11:27.676468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66c463bfaf2'
down_revision = 'a73fd712eb63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
