"""test1

Revision ID: a73fd712eb63
Revises: c2ad4688b920
Create Date: 2023-10-17 03:05:13.981253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73fd712eb63'
down_revision = 'c2ad4688b920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupations', sa.Column('cons_fre', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('role_wine', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('life_style', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('wine_taste', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('reputation', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('per_week', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('new_wine', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('friend_gather', sa.Float(), nullable=True))
    op.add_column('occupations', sa.Column('visit_winery', sa.Float(), nullable=True))
    op.drop_column('occupations', 'context_deal_with_unpleasant_or_angry_people')
    op.drop_column('occupations', 'context_duration_of_typical_work_week')
    op.drop_column('occupations', 'style_independence')
    op.drop_column('occupations', 'style_social_orientation')
    op.drop_column('occupations', 'style_achievement_effort')
    op.drop_column('occupations', 'context_outdoors_exposed_to_weather')
    op.drop_column('occupations', 'context_exposed_to_hazardous_conditions')
    op.drop_column('occupations', 'style_stress_tolerance')
    op.drop_column('occupations', 'style_innovation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupations', sa.Column('style_innovation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('style_stress_tolerance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('context_exposed_to_hazardous_conditions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('context_outdoors_exposed_to_weather', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('style_achievement_effort', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('style_social_orientation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('style_independence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('context_duration_of_typical_work_week', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('occupations', sa.Column('context_deal_with_unpleasant_or_angry_people', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('occupations', 'visit_winery')
    op.drop_column('occupations', 'friend_gather')
    op.drop_column('occupations', 'new_wine')
    op.drop_column('occupations', 'per_week')
    op.drop_column('occupations', 'reputation')
    op.drop_column('occupations', 'wine_taste')
    op.drop_column('occupations', 'life_style')
    op.drop_column('occupations', 'role_wine')
    op.drop_column('occupations', 'cons_fre')
    # ### end Alembic commands ###
