"""Add cip_programs, cip_occupations table

Revision ID: c2ad4688b920
Revises: a197b5118a26
Create Date: 2023-05-11 08:19:31.929637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ad4688b920'
down_revision = 'a197b5118a26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cip_occupations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('occupation_id', sa.String(), nullable=True),
    sa.Column('cip_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cip_id'], ['cips.id'], ),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cip_programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('cip_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cip_id'], ['cips.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cip_programs')
    op.drop_table('cip_occupations')
    # ### end Alembic commands ###
